### ISSUE TITLE
Zeta Crashes on Load

### ISSUE THREAD

**Issue by MadSciSlack** [VazkiiMods/Zeta#11]
Zeta apparently is required by Integrated Dungeons and Structures now, and is crashing my client on load.  Hopefully this is helpful, as I know this is a newer project.  It's possible that Zeta clashes with FancyMenu's implementation, as none of the "cowardly" errors were present in logs before this.

Crash Report & Debug Log
https://pastebin.com/aYbfZ3fc
[debug.log](https://github.com/VazkiiMods/Zeta/files/14625116/debug.log)

Best regards,

- Slack

**Comment by katubug** [comment]
I came here to report this same issue.

**Comment by katubug** [comment]
Aha. I had a suspicion that Curseforge just installed Zeta when I updated Quark, because newer versions of Quark list it as a dependency. When I went to see if I could roll it back to a previous version, it said there were no versions available, which confirmed my suspicions a bit. I disabled Zeta and the game loads just fine. Cursedforge issue I guess.
