### ISSUE TITLE
Zeta Extremely High Memory Usage

### ISSUE THREAD

**Issue by SlayDigger** [VazkiiMods/Zeta#8]
Playing with my own little WIP modpack and for some reason my memory usage was extremely high. Decided to check out the spark report and this was my results: [here](https://spark.lucko.me/BzUp2l4N8R)
Latest.log if it helps any bit: (Not uploaded as a gist due to massive file size) [here](https://drive.google.com/file/d/1yozoMIUY-X_1Nb8KEuMtBIphlBYOIUvD/view?usp=sharing)

**Comment by Siuolplex** [comment]
Posting research here for personal reference

The issue here is a mix of CreativeTabs being constantly reloaded (Probably not us? Thinking its Owolib) and the fact that when we do creative tab stuff we run a registry look for every block item. We MIGHT be able to just throw a reference to the block item in the class, but the way of doing so that Im thinking is a horrible idea.
